### ISSUE TITLE
Right way to add deps when starting REPL from emacs

### ISSUE THREAD

**Issue by didibus** [clojure-emacs/inf-clojure#185]
I tried running `inf-clojure` and using command `clojure -Sdeps '{:deps {org.clojure/math.combinatorics {:mvn/version "0.1.6"}}}'` but it fails with:

```
Error building classpath. Don't know how to create ISeq from: clojure.lang.Symbol
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
	at clojure.lang.RT.seqFrom(RT.java:557)
	at clojure.lang.RT.seq(RT.java:537)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$merge_with$merge2__5964.invoke(core.clj:3066)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core$reduce1.invokeStatic(core.clj:942)
	at clojure.core$reduce1.invokeStatic(core.clj:934)
	at clojure.core$merge_with.invokeStatic(core.clj:3059)
	at clojure.core$merge_with.doInvoke(core.clj:3051)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.tools.deps.alpha.reader$merge_deps.invokeStatic(reader.clj:87)
	at clojure.tools.deps.alpha.reader$merge_deps.invoke(reader.clj:84)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:91)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:74)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:117)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:111)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:162)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:134)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

I havn't been able to find a successful way to launch the clojure REPL from `inf-clojure` but in a way I can pass some additional deps as so. What's the right way to do this?

**Comment by bbatsov** [comment]
Probably something's wrong with the quoting of the command that gets executed by Emacs? @dpsutton might be able to help you, as I don't use tools.deps myself.
